export const en = {
    General: 'General',
    Keymap:'Keymap',
    Global_Keyboard_Shortcut: 'Global Keyboard Shortcut',
    Enable_Global_Hotkey: 'Enable Global Hotkey',
    Window_Application: 'Window/Application',
    Show_in_dock: 'Show in dock',
    Show_in_menu_bar: ' Show in menu bar',
    Always_on_top: 'Always on top',
    Buffer_File_Path: 'Buffer File Path',
    Use_custom_buffer_file_location: 'Use custom buffer file location',
    change_language: 'Change Language',
    Select_Directory: 'Select Directory',
    Editing: 'Editing', 
    Input_settings: 'Input settings',
    Auto_close_brackets_and_quotation_marks: 'Auto-close brackets and quotation marks',
    Appearance: 'Appearance',
    Gutters: 'Gutters',
    Show_line_numbers: 'Show line numbers',
    Show_fold_gutter: 'Show fold gutter',
    Font_Family: 'Font Family',
    Font_Size: 'Font Size',
    Current_Version: 'Current Version',
    Auto_Update: 'Auto Update',
    Periodically_check_for_new_updates: 'Periodically check for new updates',
    Beta_Versions: 'Beta Versions',
    Use_beta_versions_of_Heynote: 'Use beta versions of Heynote',
    Updates: 'Updates',
    Version:'Version'
  };