// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  NoteContent = 1,
  Document = 2,
  Note = 3,
  NoteDelimiter = 4,
  NoteLanguage = 5,
  Auto = 6,
  Metadata = 7,
  MetadataEntry = 8,
  MetadataSeparator = 9,
  MetadataKey = 10,
  MetadataEq = 11,
  MetadataValue = 12
