export const zh={ 
    General: '常用',
    Keymap:'快捷键',
    Global_Keyboard_Shortcut: '全局快捷键',
    Enable_Global_Hotkey: '启用全局快捷键',
    Window_Application: '窗口/应用',
    Show_in_dock: '显示在任务栏',
    Show_in_menu_bar: ' 显示在菜单栏',
    Always_on_top: '置顶',
    Buffer_File_Path: '缓存文件路径',
    Use_custom_buffer_file_location: '使用自定义缓存文件位置',
    change_language: '切换语言',
    Select_Directory: '选择目录',
    Editing: '编辑',
    Input_settings: '输入设置',
    Auto_close_brackets_and_quotation_marks: '自动关闭括号和引号',
    Appearance: '外观',
    Gutters: '边栏',
    Show_line_numbers: '显示行号',
    Show_fold_gutter: '显示折叠边栏',
    Font_Family: '字体',
    Font_Size: '字号',
    Current_Version: '当前版本',
    Auto_Update: '自动更新',
    Periodically_check_for_new_updates: '定期检查新版本',
    Beta_Versions: '测试版本',
    Use_beta_versions_of_Heynote: '使用 Heynote 测试版本',
    Updates: '更新',
    Version:'版本'
}